services:
  api:
    build: .
    container_name: ai_chatbot_api
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python -m alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:16
    container_name: ai_chatbot_db
    environment:
      POSTGRES_DB: simple_chatbot
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_password
    ports:
      - "5432:5432"
    volumes:
      - chatbot_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d simple_chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5


  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ai_chatbot_jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  chatbot_postgres_data: